services:
- docker

env:
  global:
    - IMAGE_NAME="pegasystems/pega-ready"
    - VERSION="2.1.0-${TRAVIS_REPO_SLUG%%/*}-$TRAVIS_BUILD_NUMBER"
    - secure: "MOKhHDWc1MyXwbzx8f+yxoZmd6ioItUOrdKYqyzz1QMV8Qs2NbJJxmeGJLNPkOt9kmfXKwSSnROzHgdmfxQ+vUHCfMbwdFvEV/4BStj6c353yyyUBS/ijJj1Wl6hf3L2N0knLDjWjJ6pOS1IxjvAQxJX3IdBAqUVZ3636SwJ1RnDysH0nyVnqcQryMm5tyOPV6mO6K7aElp36JsLb2g0yV7Ib62O2M0HtfNZrczUa7QwVXYe3neiAIuXz+Bcmqno3ya2TGD4dmFuvHcADZHfOVkuTPC3CM30om8xV/kmqqS07yLqxMTQXze9pAuBZx1NTWIkSbtkV/ydyqn/7ZNz7468BMBA/1baCEBBj+qBxnl5EE/AO0ao7bnvhZxJcXLgio9FzzO88WKDFUeEWVREj+CVhKPzKt1sfeQWwszM+RF4qmaNOEBcon3ZYalZ1svntTXidgXUrYbvcxBdbdV0MeAW+79kFstIjiaOgW+OkTYpB+lZqmyiVCLbGqoMSjKdpGrsz+4wA8+r5MqDHvTB/LE9gX6w1PFJCKUOl2tYWwo8S8fQEYj91A1KnZqE8PtHo98qloB4EDTQJ9KBEeM3w+9G1S3OwtbRnIElq9fOmJWFPGZtzPQgmahwhBRSE/fPzR33G5RbPOf5RlPm8WCF9W+OtWtnzoOBd5+X3lKOVak="
    - secure: "NLrhD/zPNha2BGcxXVlyRn1Dln111MHqgvoLpYr7Id/KmKHgcSMrrftMM5yEhqtaMlHABFUwnWfLZQinIGCy8oPkE9VuGLjQnx+axYBO2szJ+t3yqz4XFU/tBqwTzgsTZOrr7pC97YakXS2ENwpeoXs+r/8XG/COn+D8DKKAt67imjThvNPhX3eljuCLfYveGfRmSmXBLtKYK0/tMZ+FiuZBR8FEH6MVVXtsvkcV5nNeuKUy+EucjfvDkvQhbjJTG7E266erTuYICgczLq4ph4wRQPA7EkjlE/cecDZyqSMQ8gymk2gVQ/iCsF80kkKUcLRcMT5iMIfT0ZEtCSEwxir0n8zphjXyn9t3iKgfa8lRjRCrR9HWgO0CQycqMzUKJZidiaKpNYkilVKz8wt/S3Pgb3GyTE8zoqnnKLBF68rEcMsI0SAsuuI49AdLh72iv3/oFmcjxWnjZaD79o09841eWzGUWqbXOYxQpg3h7eOPEGaagmDmXyZmatQCKlMkqyKxanMcpE8CSPVeVVe3qsmEHK++yccJoZZOUSdoI5eJTJAIG9J28rxULKeHIKt1Q31KP5B+oiEqFwADlMiFhj+RcesRRmvIBHNSp6l958B9lB4eGYETxuhV9b+tTpOahpkWGN1bzQeU1JaY0LyR45RUi+3nBC+i0obMaRHchTU="
install:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" || true
  - curl -L https://github.com/arminc/clair-scanner/releases/download/v8/clair-scanner_linux_amd64 > clair-scanner
  - chmod +x clair-scanner
  - sudo mv clair-scanner /usr/local/bin
  - docker run -d --name db arminc/clair-db
  - docker run -p 6060:6060 --link db:postgres -d --name clair arminc/clair-local-scan:v2.0.6
  - curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && chmod +x container-structure-test-linux-amd64 && sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
  
script:
  - make test
  - docker images
  - clair-scanner -w tests/cve-scan-whitelist.yaml -c "http://127.0.0.1:6060" --threshold="High" --ip "$(ip -4 addr show docker0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')" $IMAGE_NAME:latest

before_deploy:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" 
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$VERSION #Tag for current version

deploy:
  provider: script
  script: make push
  on:
    repo: pegasystems/docker-pega-web-ready
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(v.+|master)$
