services:
- docker

env:
  global:
    - IMAGE_NAME="pegasystems/pega-ready"
    - VERSION="2.1.0-${TRAVIS_REPO_SLUG%%/*}-$TRAVIS_BUILD_NUMBER"
    - secure: "gaXn5/TvuBYhCH5jXKTMiUPrZSAj6y6ik9VDH6JIrd7n3RhHKehVe9MtBiGs+JA6Y7ozAHbPFKRmVd+hNIEDkpuwxbgvqn31B9vZemsLltFu66L7QUw8TSzHV+Uk35+xbia0MyERSH0HXhaRtnqrUtbEQ+XqJs5g8bnXQeCJ41jWHpUb5RiMDoaSLVwRsovl7nXovA2u6DRqARsGLVwAPihRWT1uvZ4DstIIx71xWTPX9iWkrcy3pCmgkU51neqPf6+MAa/iLzR3Uy0CUhG02OQdivpG67+21xU/R6LGvP5VLNG5sXx52QJuic73UmiLJk+A2yzLr/zL+k7nJi86zbhEnEWXF8OWJ0xfqz7hElXlHuCEomNXYYQdB1BKli7vvO2xzwj/h9q/CN+yssNPydOrJc8Psw90U9Gy6QKJ/DvfTKOqAWJu/WCsZEbEwNqW9L7N4OJoDRvBXQkfpvjCNXVEUBf5AE8ReoDo76sMssBXV8E3XEquAVfciJq9gCUqpzPtDObLr54/WXZ1ZGb9uSfaI3xH60qDSuk85Tuva034Nok7uE5bgANbeSmaH35GfkFjA/eDAynJLxJnfvtwoDLiWD5PXRoxNY72nsk8RuwtMYimUfRKS0MwiY4RQQjNcWxILcGIB756i3TNxxq25Kn2jNJx9h/3dRXMy9S2MTA="
    - secure: "SFt5o77Mime/Zk10fsCsDls2o07TI7NJg+o26Mdt1utbojuSUlK5JfOSgLukz1zTGjTHekLRTkpTvnmCOKtKyAzhIrgG6oIFSSw//TDeIRlGx10sg8IqhBmuoQkOcqMp2t48yX0UDLUNTY5E3WD+aaYU1wHKM8XIRAGKOlEn1Zm7l0vrnzWiOsAPpqbxa2xgI1TLPAvm6dVPLjnZqIgl/l29xBWb0gTZ02Km78gBBQYqA6FlbvJcMBczDG9ZPh5D/qI4aM5cKKyY0MfXaSlnRxHavSsinWxA3DyZrTM5oh7de1+YGk/VzaYt6PE0o/ExTs0bfeI14UZXqYdorvK4YRhLb2jaLnf4piwVGrmbvjXT0S7sP+OeSSTpPwUgiIRuE1sdqYKUolWuCvZA9Owj++Nxo6XS5EwDfW1zvVqWcl69kcZS+X1V5h4OsS8aWavwnT7pE7wNGwudXBF+HS1lY7IlwpzVJ2udw2iJfOVNDW5ZfgLlPuxl5km4gRs7oW7doNqEDLWBJSPz7EnnsMs8UJC5ivEmamQrLnldFKacBq/0OtaPYCw6DKrRbRu9JakNE8Ur2QMPCd2YeYCnYuedbm+8fvtpSMLszMEV5CUq5VrOLJzTHpwhGawxRYAV0zuj8ApCcTDNFat5Fkp9GuQDOq3XuCi5NlhNChxE2sfSNbQ="

install:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" || true
  - curl -L https://github.com/arminc/clair-scanner/releases/download/v8/clair-scanner_linux_amd64 > clair-scanner
  - chmod +x clair-scanner
  - sudo mv clair-scanner /usr/local/bin
  - docker run -d --name db arminc/clair-db
  - docker run -p 6060:6060 --link db:postgres -d --name clair arminc/clair-local-scan:v2.0.6
  - curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && chmod +x container-structure-test-linux-amd64 && sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
  
script:
  - make test
  - docker images
  - clair-scanner -w tests/cve-scan-whitelist.yaml -c "http://127.0.0.1:6060" --threshold="High" --ip "$(ip -4 addr show docker0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')" $IMAGE_NAME:latest

before_deploy:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" 
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$VERSION #Tag for current version

deploy:
  provider: script
  script: make push
  on:
    repo: pegasystems/docker-pega-web-ready
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(v.+|master)$
